services:
  aptabase:
    container_name: aptabase_app
    image: test/aptabase
    restart: always
    depends_on:
      - aptabase_events_db
      - aptabase_db
    ports:
      - 8000:8080
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    env_file:
      - .env
    environment:
      # Override any environment-specific variables here if needed
      # All other variables will be loaded from .env file
      ASPNETCORE_ENVIRONMENT: Production

  aptabase_db:
    container_name: aptabase_db
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    # Only include the specific postgres environment variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  aptabase_events_db:
    container_name: aptabase_events_db
    image: clickhouse/clickhouse-server:23.10.4.25
    restart: always
    volumes:
      - events-db-data:/var/lib/clickhouse
    env_file:
      - .env
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  db-data:
    driver: local
  events-db-data:
    driver: local
  dataprotection-keys:
    driver: local
